import type { Metadata } from 'next'
import '../globals.css'
import Navbar from '../components/ui/Navbar'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ weight: '400', subsets: ['latin'], display: 'swap' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: Readonly<{ children: React.ReactNode }>): JSX.Element {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}
    <Navbar />
    {children}
    </body>
    </html>
  )
}
